##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.5.0-RC5] date: [Fri Mar 20 10:09:13 EET 2026] 
#########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = scstepper


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -O0


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/eeprom_emul_uint32_t.c \
Core/Src/firmware_crc.c \
Core/Src/main.c \
Core/Src/stm32f4xx_it.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/stepper.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Core/Src/system_stm32f4xx.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
USB_DEVICE/App/usb_device.c \
USB_DEVICE/App/usbd_desc.c \
USB_DEVICE/App/usbd_cdc_if.c \
USB_DEVICE/Target/usbd_conf.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f411xe.s

# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# Git version
GIT_HASH := $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_DIRTY := $(shell git diff --quiet 2>/dev/null || echo "-dirty")
BUILD_DATE := $(shell date '+%Y-%m-%d_%H:%M')

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F411xE \
-DGIT_HASH=\"$(GIT_HASH)$(GIT_DIRTY)\" \
-DBUILD_DATE=\"$(BUILD_DATE)\"


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IUSB_DEVICE/App \
-IUSB_DEVICE/Target \
-IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc \
-IMiddlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Werror -Wall -Wextra -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Werror -Wall -Wextra -fdata-sections -ffunction-sections -include Core/Inc/defines.h

ifeq ($(DEBUG), 1)
CFLAGS += -g3 -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = stm32f411ceux_flash.ld

# libraries
LIBS = -lc -lm -lnosys
LIBDIR =
# Suppress false-positive linker warning for .data AT>FLASH (older ld doesn't know this flag)
NO_WARN_RWX := $(shell $(PREFIX)ld --help 2>&1 | grep -q no-warn-rwx-segments && echo -Wl,--no-warn-rwx-segments)
LDFLAGS = $(MCU) -specs=nano.specs -specs=nosys.specs -u _printf_float -u _scanf_float -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections $(NO_WARN_RWX)

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

# CubeMX/HAL-generated files with intentional unused parameters — silence locally
$(BUILD_DIR)/usbd_conf.o: USB_DEVICE/Target/usbd_conf.c Makefile | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) -Wno-unused-parameter -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/stm32f4xx_hal_flash_ex.o: Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c Makefile | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) -Wno-unused-parameter -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

# CRC patch: .bin rule generates both bin and hex, then patches CRC word.
# .hex depends on .bin so make runs .bin first when both are in 'all'.
$(BUILD_DIR)/$(TARGET).bin: $(BUILD_DIR)/$(TARGET).elf | $(BUILD_DIR)
	$(BIN) $< $@
	$(HEX) $< $(BUILD_DIR)/$(TARGET).hex
	@python3 scripts/crc_patch.py $< $@ $(BUILD_DIR)/$(TARGET).hex

$(BUILD_DIR)/$(TARGET).hex: $(BUILD_DIR)/$(TARGET).bin
	@: # generated and CRC-patched by the .bin rule above

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

#######################################
# Developer environment install — two targets:
#   make userinstall  — no root needed (files stay in/near project)
#   make sysinstall   — root needed (copies files outside project)
# Override: make sysinstall UDEV_DIR=/path
#######################################
UDEV_DIR ?= /etc/udev/rules.d

.PHONY: userinstall
userinstall:
	@echo ""
	@echo "=== User install ==="
	@echo ""
	@echo "--- [1/3] $(HOME)/.gdbinit (GDB auto-load enable) ---"
	@cp -v initcfg/dot-gdbinit-for-home $(HOME)/.gdbinit
	@echo ""
	@echo "--- [2/3] GDB Dashboard panel -> $(HOME)/.gdbinit.d/ ---"
	@mkdir -p $(HOME)/.gdbinit.d
	@cp -v initcfg/scstepper_panel.py $(HOME)/.gdbinit.d/scstepper_panel.py
	@echo ""
	@echo "--- [3/3] Qt Creator + clangd files (make qtc) ---"
	@$(MAKE) --no-print-directory qtc
	@echo ""
	@echo "======== USER INSTALL OK ========"
	@echo ""
	@echo "  Open qtc/scstepper.creator in Qt Creator"
	@echo "  clangd uses compile_commands.json automatically"
	@echo "  GDB Dashboard panel 'scstepper' loaded from ~/.gdbinit.d/"
	@echo ""

.PHONY: sysinstall
sysinstall:
	@echo ""
	@echo "=== System install (run as root) ==="
	@echo ""
	@echo "--- [1/1] udev rules -> $(UDEV_DIR) ---"
	@cp -v scripts/99-steppersys.rules $(UDEV_DIR)/99-steppersys.rules
	@udevadm control --reload-rules
	@echo "udev rules reloaded"
	@echo ""
	@echo "======== SYS INSTALL OK ========"
	@echo ""

#######################################
# Qt Creator / clangd project files
#######################################
.PHONY: qtc
qtc:
	python3 scripts/gen_qtc.py

#######################################
# post-CubeMX regeneration fixup
#######################################
.PHONY: post_cubemx
post_cubemx:
	bash scripts/post_cubemx.sh

.PHONY: size
size: $(BUILD_DIR)/$(TARGET).elf
	$(SZ) --format=berkeley $<

#######################################
# check vs template + post_cubemx patches
#######################################
check:
	@FAIL=0; \
	if diff -q Makefile Makefile.template > /dev/null 2>&1; then \
		echo "  [OK]  Makefile matches template"; \
	else \
		echo "  [FAIL] Makefile differs from Makefile.template — run: bash scripts/post_cubemx.sh"; \
		FAIL=1; \
	fi; \
	if grep -qE 'GPIO_MODE_IT_RISING[^_]|GPIO_MODE_IT_FALLING[^_]' Core/Src/main.c; then \
		echo "  [FAIL] GPIO_MODE_IT_RISING/FALLING not patched in main.c — run: bash scripts/post_cubemx.sh"; \
		FAIL=1; \
	else \
		echo "  [OK]  GPIO_MODE_IT_RISING_FALLING patch applied"; \
	fi; \
	GHOST=$$(grep -rhoE '\b(esBlocked|initParams|writeParams|readParams|ProcessLineOld)\b' initcfg/ scripts/ 2>/dev/null | tr '\n' ' '); \
	if [ -n "$$GHOST" ]; then \
		echo "  [FAIL] GDB scripts reference removed firmware symbols: $$GHOST"; \
		FAIL=1; \
	else \
		echo "  [OK]  GDB scripts: no stale firmware symbol references"; \
	fi; \
	if [ $$FAIL -eq 0 ]; then \
		echo ""; echo "======== CHECK OK ========"; echo ""; \
	else \
		echo ""; echo "======== CHECK FAILED — see above ========"; echo ""; exit 1; \
	fi
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
