#!/usr/bin/env python3
"""
gen_qtc.py — generate Qt Creator project files + compile_commands.json + .clangd
Run via: make qtc  (from project root)

Outputs:
  compile_commands.json   — clangd compile database (project root)
  .clangd                 — clangd flag fixups for ARM bare-metal (project root)
  qtc/scstepper.creator   — Qt Creator generic project marker
  qtc/scstepper.files     — all .c/.h/.s source files
  qtc/scstepper.includes  — include paths
  qtc/scstepper.config    — preprocessor defines for Qt Creator code model
"""

import subprocess, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def run_make_dry():
    """Run 'make -n' and return lines."""
    r = subprocess.run(
        ['make', '-n', '--no-print-directory'],
        capture_output=True, text=True, cwd=ROOT
    )
    return r.stdout.splitlines()

def parse_compile_commands(lines):
    """Extract compile commands from make -n output."""
    commands = []
    for line in lines:
        if 'arm-none-eabi-gcc -c' not in line:
            continue
        # Find source file: last .c argument before -o
        m = re.search(r'(\S+\.c)\s+-o\s+\S+', line)
        if not m:
            continue
        src = m.group(1)
        src_abs = os.path.normpath(os.path.join(ROOT, src))
        commands.append({
            "directory": ROOT,
            "command":   line.strip(),
            "file":      src_abs
        })
    return commands

def write_compile_commands(commands):
    path = os.path.join(ROOT, 'compile_commands.json')
    with open(path, 'w') as f:
        json.dump(commands, f, indent=2)
    print(f"  compile_commands.json  ({len(commands)} files)")

def write_clangd():
    """Write .clangd to strip GCC/assembler flags clangd doesn't understand."""
    content = """\
# .clangd — ARM bare-metal flag fixups for clangd
# Removes GCC-specific flags that clang/clangd does not support.
CompileFlags:
  Add:
    - --target=arm-none-eabi
  Remove:
    - -mcpu=*
    - -mthumb
    - -mfpu=*
    - -mfloat-abi=*
    - -specs=*
    - -Wa,-a,-ad,-alms=*
    - -MMD
    - -MP
    - -MF*
    - -dM
    - -Werror
"""
    path = os.path.join(ROOT, '.clangd')
    with open(path, 'w') as f:
        f.write(content)
    print(f"  .clangd")

def collect_files():
    """Collect all .c, .h, .s, .S source files."""
    files = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        # skip build/ and hidden dirs
        dirnames[:] = [d for d in dirnames if d != 'build' and not d.startswith('.')]
        for fn in filenames:
            if fn.endswith(('.c', '.h', '.s', '.S', '.ld')):
                rel = os.path.relpath(os.path.join(dirpath, fn), ROOT)
                files.append(rel)
    files.append('Makefile')
    files.sort()
    return files

def collect_includes(commands):
    """Extract unique -I include paths from compile commands."""
    includes = set()
    for cmd in commands:
        for m in re.finditer(r'-I(\S+)', cmd['command']):
            inc = m.group(1)
            # make absolute
            if not os.path.isabs(inc):
                inc = os.path.normpath(os.path.join(ROOT, inc))
            includes.add(inc)
    return sorted(includes)

def collect_defines(commands):
    """Extract -D defines from compile commands (skip dynamic ones with quotes)."""
    defines = set()
    skip = ('GIT_HASH', 'BUILD_DATE')
    for cmd in commands:
        for m in re.finditer(r'-D(\S+)', cmd['command']):
            d = m.group(1)
            if not any(d.startswith(s) for s in skip):
                defines.add(d)
    return sorted(defines)

def write_qtc(files, includes, defines):
    qtc_dir = os.path.join(ROOT, 'qtc')
    os.makedirs(qtc_dir, exist_ok=True)
    name = 'scstepper'

    # .creator
    with open(os.path.join(qtc_dir, f'{name}.creator'), 'w') as f:
        f.write('[General]\n')

    # .files — paths relative to qtc/
    with open(os.path.join(qtc_dir, f'{name}.files'), 'w') as f:
        for fn in files:
            f.write(f'../{fn}\n')

    # .includes — absolute paths (most reliable for Qt Creator)
    with open(os.path.join(qtc_dir, f'{name}.includes'), 'w') as f:
        for inc in includes:
            f.write(f'{inc}\n')

    # .config — preprocessor defines
    with open(os.path.join(qtc_dir, f'{name}.config'), 'w') as f:
        f.write('// Auto-generated by gen_qtc.py — do not edit\n')
        for d in defines:
            if '=' in d:
                k, v = d.split('=', 1)
                f.write(f'#define {k} {v}\n')
            else:
                f.write(f'#define {d}\n')

    print(f"  qtc/{name}.creator")
    print(f"  qtc/{name}.files     ({len(files)} files)")
    print(f"  qtc/{name}.includes  ({len(includes)} paths)")
    print(f"  qtc/{name}.config    ({len(defines)} defines)")

def main():
    print("=== gen_qtc ===")
    lines    = run_make_dry()
    commands = parse_compile_commands(lines)
    if not commands:
        print("ERROR: no compile commands found — run 'make' first to create build/", file=sys.stderr)
        sys.exit(1)

    write_compile_commands(commands)
    write_clangd()

    files    = collect_files()
    includes = collect_includes(commands)
    defines  = collect_defines(commands)
    write_qtc(files, includes, defines)

    print("")
    print("======== CHECK OK ========")
    print("")
    print("Open qtc/scstepper.creator in Qt Creator.")
    print("clangd will use compile_commands.json automatically.")

if __name__ == '__main__':
    main()
